#!/usr/bin/env python

#
#
#
#
#
#import os
#import sys


#loads modules
import sys
import subprocess
import os
import time

#password authentication to run script has been created into an "if" statement
validPassword = 'penis' #this is our password.

inputPassword = raw_input('Please Enter Password: ')

if inputPassword == validPassword:
    print 'You have access!'
else:
    print 'Access denied!'
    sys.exit(0)

print 'Hello there! Let me start pinging that dank ass range you selected!'
print 'Waiting...'


#delay for 3 seconds
time.sleep(3)


for ping in range(139,145):
    address = "10.0.148." + str(ping)
    res = subprocess.call(['ping', '-c', '3', address])
    if res == 0:
        print "ping to", address, "OK"
    elif res == 2:
        print "no response from", address
    else:
        print "ping to", address, "failed!"



with open(os.devnull, "wb") as limbo:
        for n in xrange(1, 10):
                ip="8.8.8.{0}".format(n)
                result=subprocess.Popen(["ping", "-c", "1", "-n", "-W", "2", ip],
                        stdout=limbo, stderr=limbo).wait()
                if result:
                        print ip, "inactive"
                else:
                        print ip, "active"

#this redirects STDOUT to a file
